version: "3"
services:
  solaredge:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.40'
          memory: 128M
      restart_policy:
        condition: any
        delay: 30s
    image: chrisns/iot-solaredge:${DRONE_BUILD_NUMBER}
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_IOT_ENDPOINT_HOST=${AWS_IOT_ENDPOINT_HOST}
      - AWS_REGION=${AWS_REGION}
      - SOLAREDGE_ENDPOINT=${SOLAREDGE_ENDPOINT}
      - INTERVAL=120
      - METERS=1
